// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ZealandKantine.Models;

public partial class CafeZea : DbContext
{
    public CafeZea()
    {
    }

    public CafeZea(DbContextOptions<CafeZea> options)
        : base(options)
    {
    }

    public virtual DbSet<DailySpecial> DailySpecials { get; set; }

    public virtual DbSet<MenuItem> MenuItems { get; set; }

    public virtual DbSet<MonthlyStatement> MonthlyStatements { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderLine> OrderLines { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<WeekMenu> WeekMenus { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=mssql10.unoeuro.com;Initial Catalog=tinysoft_dk_db_test;Persist Security Info=True;User ID=tinysoft_dk;Password=3DR96zepFB4HGnamEryw");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DailySpecial>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DailySpe__3214EC07CEC4ABAC");
        });

        modelBuilder.Entity<MenuItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MenuItem__3214EC0740B3A360");
        });

        modelBuilder.Entity<MonthlyStatement>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MonthlyS__3214EC07F9B4A6C2");

            entity.HasOne(d => d.User).WithMany(p => p.MonthlyStatements)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MonthlyStatement_ToUser");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC078E96CB1E");

            entity.HasOne(d => d.User).WithMany(p => p.Orders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Order_User");
        });

        modelBuilder.Entity<OrderLine>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC07EF6F7874");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderLines)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderLine_Order");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__User__3214EC0776D2FD20");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<WeekMenu>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC07E5B45471");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}