// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ZealandKantine.Models;

[Table("DailySpecial")]
public partial class DailySpecial
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Description { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Price { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("DailySpecial")]
    public virtual ICollection<MenuDaySpecial> MenuDaySpecials { get; set; } = new List<MenuDaySpecial>();

    [InverseProperty("DailySpecial")]
    public virtual ICollection<OrderLine> OrderLines { get; set; } = new List<OrderLine>();
}