// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ZealandKantine.Models;

[Table("MenuItem")]
public partial class MenuItem
{
    [Key]
    public int Id { get; set; }

    [Required]
    [Column("Name")]
    [StringLength(50)]
    public string Name { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal Price { get; set; }

    public MenuCategory Category { get; set; }
    public bool IsActive { get; set; }
}