// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ZealandKantine.Models;

[Table("MenuItem")]
public partial class MenuItem
{
    public enum MenuCategory
    {
        Sandwich,
        Snack,
        Drink
    }
    public class MenuItem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public MenuCategory Category { get; set; }
        public bool IsActive { get; set; }

    public bool IsActive { get; set; }
}