// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ZealandKantine.Models;

[Table("MenuDay")]
public partial class MenuDay
{
    [Key]
    public int Id { get; set; }

    public int WeekMenuId { get; set; }

    public byte DayOfWeek { get; set; }

    public DateOnly Date { get; set; }

    [InverseProperty("MenuDay")]
    public virtual ICollection<DailySpecial> DailySpecials { get; set; } = new List<DailySpecial>();

    [ForeignKey("WeekMenuId")]
    [InverseProperty("MenuDays")]
    public virtual WeekMenu WeekMenu { get; set; }
}