// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ZealandKantine.Models;

[Table("MenuDaySpecial")]
[Index("MenuDayId", "DailySpecialId", Name = "UQ_MenuDaySpecial", IsUnique = true)]
public partial class MenuDaySpecial
{
    [Key]
    public int Id { get; set; }

    public int MenuDayId { get; set; }

    public int DailySpecialId { get; set; }

    [ForeignKey("DailySpecialId")]
    [InverseProperty("MenuDaySpecials")]
    public virtual DailySpecial DailySpecial { get; set; }

    [ForeignKey("MenuDayId")]
    [InverseProperty("MenuDaySpecials")]
    public virtual MenuDay MenuDay { get; set; }
}