// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ZealandKantine.Models;

[Table("MonthlyStatement")]
public partial class MonthlyStatement
{
    [Key]
    public int Id { get; set; }

    public int Userid { get; set; }

    public int Month { get; set; }

    public int Year { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal TotalAmount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime GeneratedAt { get; set; }

    [ForeignKey("Userid")]
    [InverseProperty("MonthlyStatements")]
    public virtual User User { get; set; }
}