// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ZealandKantine.Models;

[Table("Order")]
public partial class Order
{
    [Key]
    public int Id { get; set; }

    public int UserId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime OrderDateTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ReadyAt { get; set; }

    [Required]
    [StringLength(50)]
    public string Status { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal NetTotal { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal DiscountTotal { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal GrossTotal { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<OrderLine> OrderLines { get; set; } = new List<OrderLine>();

    [ForeignKey("UserId")]
    [InverseProperty("Orders")]
    public virtual User User { get; set; }
}