// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ZealandKantine.Models;

[Table("OrderLine")]
public partial class OrderLine
{
    [Key]
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int Month { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal UnitPrice { get; set; }

    public int DiscountPercent { get; set; }

    public int MenuItem { get; set; }

    public int DailySpecial { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal DiscountAmount { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderLines")]
    public virtual Order Order { get; set; }
}