// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ZealandKantine.Models;

[Table("WeekMenu")]
public partial class WeekMenu
{
    [Key]
    public int Id { get; set; }

    public int WeekNumber { get; set; }

    public int Year { get; set; }

    public bool IsPublished { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EmailSentAt { get; set; }

    [InverseProperty("WeekMenu")]
    public virtual ICollection<MenuDay> MenuDays { get; set; } = new List<MenuDay>();
}